spring.application.name=ecommerce-api
spring.datasource.url=jdbc:mysql://localhost:3306/mu25_ecommerce
spring.datasource.username=root
spring.datasource.password=root541201
spring.jpa.hibernate.ddl-auto=validate
app.persistence.refresh-after-save=true
app.persistence.mode=jpa